version: 2.1

defaults: &defaults
  working_directory: ~/130-project/9
  docker:
    - image: circleci/node:10.14.2

orbs:
  node: circleci/node@3.0.0

jobs:
    build:
      docker:
              - image: circleci/node:10.14.2
      steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
    #test:
      #steps:
        #- run: npm ci
        # - run: npm run build
        #- run: npm run test:ci
      
        #- save_cache:
        #  paths:
        #    - node_modules
        #  key: v1-dependencies-{{ checksum "package.json" }}

workflows:
     build_and_test:
        jobs:
          - build
          
          #- test
