version: 2.1

defaults: &defaults
  working_directory: ~/130-project/9
  docker:
    - image: circleci/node:10.14.2

orbs:
  node: circleci/node@3.0.0

jobs:
  core:
    <<: *defaults
    working_directory: ~/130-project/9

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
        # - run: npm run build
      - run: npm run test:ci
      - run: npm run start
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
