version: 2.1

defaults: &defaults
  working_directory: ~/130-project/9
  docker:
    - image: circleci/node:10.14.2

orbs:
  node: circleci/node@3.0.0

jobs:
    build:
      docker:
              - image: circleci/node:10.14.2
      steps:
      - checkout
      # Download and cache dependencies
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm ci
      - run: npm install

      - persist_to_workspace:
        root: ../opencourse-backend
        paths:
          - node_modules
              
      - run: npm run build
    #test:
      #steps:
        #- run: npm run test:ci
      
        #- save_cache:
        #  paths:
        #    - node_modules
        #  key: v1-dependencies-{{ checksum "package.json" }}

workflows:
     build_and_test:
        jobs:
          - build
          
          #- test
