version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
    build:
      docker:
      - image: circleci/node@3.0.0
      steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
    test:
      - run: npm ci
        # - run: npm run build
      - run: npm run test:ci
      
        #- save_cache:
        #  paths:
        #    - node_modules
        #  key: v1-dependencies-{{ checksum "package.json" }}

workflows:
     build_and_test:
        jobs:
          - build
          - test
